empleado/applications/departamento/urls.py
from django.urls import path
from .views import NewDepartamentoView,DepartamentoListView

def DesdeApp(self):
    print('====================Desde aplicación Departamento==================================')

app_name='departamento_app'
urlpatterns = [
    path(
        'departamento-lista/',
        DepartamentoListView.as_view(),
        name='departamento_list'
        ),
    path('new-departamento/',NewDepartamentoView.as_view(),name='nuevo_departamento'),
]

empleado/applications/persona/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


from .views import (
    ListAllEmpleados,
    ListByAreaEmpleado,
    ListEmpleadoByKword,
    ListByTrabajoEmpleado,
    ListHabilidadesEmpleados,
    EmpleadoDetailView,
    EmpleadoCreateView,
    SuccessView,
    EmpleadoUpdateView,
    EmpleadoDeleteView,
    InicioView,
    ListEmpleadosAdmin

)

app_name='persona_app' #estandar de nombre usado por la comunidad
urlpatterns = [
    path('',InicioView.as_view(),name='inicio'),
    path(
        'listar-todo-empleados/',
        ListAllEmpleados.as_view(),
        name="empleados_all"
        ),
    path(
        'listar-by-area/<shorname>/',
         ListByAreaEmpleado.as_view(),
          name='empleados_area'
          ),
    path(
        'lista-empleados-admin/',
         ListEmpleadosAdmin.as_view(),
          name='lista_empleados'
          ),
    path('buscar-empleado/',ListEmpleadoByKword.as_view()),
    path('listar-by-job/', ListByTrabajoEmpleado.as_view()),
    path('listar-habilidades/', ListHabilidadesEmpleados.as_view()),
    path('detail-empleado/<pk>/', EmpleadoDetailView.as_view(), name="detail_empleado"),
    path(
        'add-empleado/',
         EmpleadoCreateView.as_view(),
         name="empleado_add"
         ),
    path('success/', SuccessView.as_view(),name='correcto'),
    path('update-empleado/<pk>',EmpleadoUpdateView.as_view(),name='modificar'),
    path('eliminar-empleado/<pk>',EmpleadoDeleteView.as_view(),name='eliminar')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path,include,re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    # include urls de aplicacion departamento
    re_path('',include('applications.departamento.urls')),
    # include urls de aplicación persona
    re_path('',include('applications.persona.urls')),
    # include urls de la aplicación home
    re_path('',include('applications.home.urls')),
    

]

empleado/templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Empleados</li>
        <li><a href="{% url 'persona_app:empleados_all' %}">Listar</a></li>
        <li><a href="{% url 'departamento_app:departamento_list' %}">Departamento</a></li>
        <li><a href="{% url 'persona_app:lista_empleados' %}">Administrar</a></li>
        <li><a href="{% url 'departamento_app:nuevo_departamento' %}">Registrar Departamento</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar Empleado"></li>
        <li><a href= "{% url 'persona_app:empleado_add'  %}" class="button">Registrar Nuevo</a></li>
      </ul>
    </div>
  </div>