empleado/applications/persona/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


from .views import (
    ListAllEmpleados,
    ListByAreaEmpleado,
    ListEmpleadoByKword,
    ListByTrabajoEmpleado,
    ListHabilidadesEmpleados,
    EmpleadoDetailView,
    EmpleadoCreateView,
    SuccessView,
    EmpleadoUpdateView,
    EmpleadoDeleteView,
    InicioView,
    ListEmpleadosAdmin

)

app_name='persona_app' #estandar de nombre usado por la comunidad
urlpatterns = [
    path('',InicioView.as_view(),name='inicio'),
    path(
        'listar-todo-empleados/',
        ListAllEmpleados.as_view(),
        name="empleados_all"
        ),
    path(
        'listar-by-area/<shorname>/',
         ListByAreaEmpleado.as_view(),
          name='empleados_area'
          ),
    path(
        'lista-empleados-admin/',
         ListEmpleadosAdmin.as_view(),
          name='lista_empleados'
          ),
    path('buscar-empleado/',ListEmpleadoByKword.as_view()),
    path('listar-by-job/', ListByTrabajoEmpleado.as_view()),
    path('listar-habilidades/', ListHabilidadesEmpleados.as_view()),
    path('detail-empleado/<pk>/', EmpleadoDetailView.as_view(), name="detail_empleado"),
    path(
        'add-empleado/',
         EmpleadoCreateView.as_view(),
         name="empleado_add"
         ),
    path('success/', SuccessView.as_view(),name='correcto'),
    path('update-empleado/<pk>',EmpleadoUpdateView.as_view(),name='modificar'),
    path('eliminar-empleado/<pk>',EmpleadoDeleteView.as_view(),name='eliminar')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path,include,re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    # include urls de aplicacion departamento
    re_path('',include('applications.departamento.urls')),
    # include urls de aplicación persona
    re_path('',include('applications.persona.urls')),
    # include urls de la aplicación home
    re_path('',include('applications.home.urls')),
    

]

empleado/applications/persona/models.py
from django.db import models
from applications.departamento.models import Departamento
from ckeditor.fields import RichTextField
# Create your models here.

class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)
    
    class Meta:
        verbose_name='Habilidad'
        verbose_name_plural='Habilidades de Empleados'
    
    def __str__(self):
        return self.habilidad

class Persona(models.Model):
    ''' Modelo para tabla Empleado'''
    JOB_CHOICE=(
        ('0','CONTADOR'),
        ('1','ADMINISTRADOR'),
        ('2', 'ECONOMISTA'),
        ('3', 'OTRO'),
    )
    first_name = models.CharField('Nombre', max_length=60)
    last_name = models.CharField('Apellido', max_length=60)
    full_name=models.CharField('Nombre completo', max_length=120,blank=True)
    job = models.CharField('Trabajo', max_length=1,choices=JOB_CHOICE)
    departamento=models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado',blank=True,null=True)
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida= RichTextField()

    class Meta:
        verbose_name='Persona'
        verbose_name_plural='Personas'
        ordering=['last_name','first_name']
        unique_together=['first_name','last_name','departamento']


    def __str__(self):
        return str(self.id) + '-' + self.first_name + ' ' + self.last_name

empleado/applications/persona/forms.py
from django import forms
from .models import Persona

class EmpleadoForm(forms.ModelForm):
    """Formulario definicion para  Persona."""

    class Meta:
        """Meta definition for EmpleadoForm."""
        model = Persona
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidades',

            )
        widgets={
            'habilidades':forms.CheckboxSelectMultiple()
        }

empleado/applications/persona/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

# models
from.models import Persona
from django.views.generic import(
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView,
)

#forms
from .forms import EmpleadoForm
# Create your views here.

class InicioView(TemplateView):
    ''' Vista que carga la pagina de inicio'''
    template_name='inicio.html'
# Create your views here.
def listar_empleados(Persona):
    listado=Persona.objects.all()
    return listado

class ListAllEmpleados(ListView):
    template_name = "persona/list_all.html"
    paginate_by=4
    ordering=['first_name',]
    context_object_name='empleados'
    #queryset=listar_empleados(Persona)
    def get_queryset(self):
        palabra_clave=self.request.GET.get("kword",'')
        queryset = Persona.objects.filter(
            full_name__icontains=palabra_clave
            )
        return queryset

class ListByAreaEmpleado(ListView):
    ''' Lista empleado de un area'''
    template_name="persona/list_by_area.html"
    context_object_name='listado'

    def get_queryset(self):
        area=self.kwargs['shorname']
        queryset = Persona.objects.filter(departamento__shor_name=area)
        return queryset
    
class ListEmpleadoByKword(ListView):
    ''' Lista empleado de un area desde formulario'''
    template_name="persona/by_kword.html"
    context_object_name='empleado'

    def get_queryset(self):
        palabra_clave=self.request.GET.get("kword",'')
        queryset = Persona.objects.filter(departamento__name=palabra_clave)
        return queryset

class ListByTrabajoEmpleado(ListView):
    ''' Lista empleado por trabajo'''
    template_name="persona/list_by_job.html"
    context_object_name='listado'

    def get_queryset(self):
        queryset = Persona.objects.filter(job='0')
        return queryset
    

class ListHabilidadesEmpleados(ListView):
    template_name="persona/habilidades.html"
    context_object_name='habilidades'

    def get_queryset(self):
        empleado = Persona.objects.get(id=4)
        return empleado.habilidades.all()


class EmpleadoDetailView(DetailView):
    model = Persona
    template_name = "persona/detail_empleado.html"

class SuccessView(TemplateView):
    template_name="persona/success.html"

class EmpleadoCreateView(CreateView):
    model = Persona
    template_name = "persona/add.html"
    form_class=EmpleadoForm
    success_url=reverse_lazy('persona_app:lista_empleados')

    def form_valid(self,form):
        persona=form.save(commit=False)
        persona.full_name=persona.first_name + ' ' + persona.last_name
        persona.save()
        return super(EmpleadoCreateView,self).form_valid(form)


class EmpleadoUpdateView(UpdateView):
    model = Persona
    template_name = "persona/update-empleado.html"
    fields=[
    'first_name',
    'last_name',
    'job',
    'departamento',
    'habilidades',
    ]
    success_url=reverse_lazy('persona_app:lista_empleados')

    def form_valid(self,form):
        persona=form.save(commit=False)
        persona.save()
        return super(EmpleadoUpdateView,self).form_valid(form)



class EmpleadoDeleteView(DeleteView):
    model = Persona
    template_name = "persona/delete.html"
    success_url=reverse_lazy('persona_app:lista_empleados')


class ListEmpleadosAdmin(ListView):
    template_name = "persona/lista_empleados.html"
    paginate_by=10
    ordering=['first_name',]
    context_object_name='empleados'
    model=Persona
    #queryset=listar_empleados(Persona)
   

empleado/templates/persona/add.html
{% extends 'base.html' %}


{% block title %}
Registrar Empleado
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Registrar Empleado
        </h1>
        <form class="cell grid-x grid-margin-x"  method="POST" enctype="multipart/form-data" >{%csrf_token%}
            <div class="medium-6 cell">
                <label>Nombre:
                  {{form.first_name}}
                </label>
            </div>
            <div class="cell medium-6">
                <label>Apellido:
                    {{form.last_name}}
                </label>
            </div>
            <div class="cell medium-6">
                <label>Trabajo:
                    {{form.job}}
                </label>
            </div>
            <div class="cell medium-6">
                <label>Departamento:
                    {{form.departamento}}
                </label>
            </div>
            <div class="cell medium-6">
                <label>Habilidades extra:
                    {{form.habilidades}}
                </label>
            </div>
            <div class="cell medium-6">
                <label>Foto:
                    {{form.avatar}}
                </label>
            </div>
            <div class="cell">
                <button type="submit" class="success button">Guardar</button>
            </div>
        </form>

    </div>

</div>
    
{% endblock content %}
    
    

empleado/templates/persona/by_kword.html
<h1>Bucar Empleado por palabra clave</h1>
<form method="GET">{%csrf_token%}
     <input type="text" id="kword" name="kword" placeholder="Ingrese nombre aqui">
     <button type="submit">Buscar</button> 
</form>

<h3>Resultado</h3>
<ul>
    {%for e in empleado%}
    <li>
       {{e}}
    </li>
    {%endfor%}
</ul>

empleado/templates/persona/delete.html
{% extends 'base.html' %}


{% block title %}
 Eliminar Empleado
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar Empleado: {{object.full_name}}</h1>
        <form class="cell" method="post">{%csrf_token%}
            <div class="callout secondary">
                <h5>¿ Esta seguro que quiere eliminar este Empleado?</h5>
                <button type="submit" class="alert button">Confirmar</button>
            </div>
            
        </form>
    </div>
</div>
    
{% endblock content %}
    
    

empleado/templates/persona/detail_empleado.html
{% extends 'base.html' %}

{% load static %} 

{% block title %}
 {{object.full_name}}
{% endblock title %}
  

{% block content %}
  {% include 'includes/header.html' %}
  <div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
      <div class="cell large-4 card" style="width: 300px;margin-top: 20px;">
        <div class="card-divider">
          {{persona.get_job_display}}
        </div>
        
        {% if persona.avatar %}
          <img src="{{persona.avatar.url}}">
        {% else %}
        <img src="{% static 'img/imagen2.jpg' %}">
        {% endif %}
        <div class="card-section">
          <h4>{{persona.full_name}}</h4>
          <p>{{persona.last_name}}</p>
          <p>{{persona.departamento.shorname}}</p>
          <p> <span class="label">Habilidades:</span></p>
          <ul class="vertical menu">
            {% for h in persona.habilidades.all %}
            <li>
              {{h.habilidad}}
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}
  
<h1> Detalle del Empleado</h1>
   {{persona}}

 <h2>Detalles Extra</h2> 
 <p>Nombre  - {{persona.first_name}}</p> 
 <p>Apellido -{{persona.last_name}}</p>
 <p>Habilidades</p>
 <div>
     <p>{{persona.habilidades}}</p>
 </div>

empleado/templates/persona/habilidades.html
<h1>Listado de Habilidades</h1>
<ul>
    {%for h in habilidades%}
    <li> {{h}} </li>
    {%endfor%}
</ul>

empleado/templates/persona/list_all.html
{% extends 'base.html' %}

{%block content%}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de Empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET">{%csrf_token%}
            <div class="cell large-7">
                <input type="text" id="kword" name= "kword" placeholder="buscar empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>
            <div class="cell">
                <table>
                    <thead>
                        <tr>
                            <th width="200">ID</th>
                            <th>NOMBRES</th>
                            <th width="150">APELLIDOS</th>
                            <th width="150">DEPARTAMENTO</th>
                            <th width="150">ACCION</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for e in empleados%}
                        <tr>
                            <td>{{e.id}}</td>
                            <td>{{e.first_name}}</td>
                            <td>{{e.last_name}}</td>
                            <td>{{e.departamento}}</td>
                            <td><a class="button warning" href="{% url 'persona_app:detail_empleado' e.id %}">Ver</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="cell">
                {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">
                      {% if page_obj.has_previous %}
                      <li class="pagination-previous">
                          <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                      </li>    
                      {% endif %}
                      {% for pagina  in paginator.page_range  %}
                      
                      {% ifequal pagina page_obj.number  %}
                      <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li> 
                      {% else %}
                      <li><a href="?page={{pagina}}" >{{pagina}}</a></li>
                      {% endifequal %}
                          
                         
                      {% endfor %}
                      {% if page_obj.has_next %}
                      <li class="pagination-next">
                          <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                     </li>
                     {% endif %}
                    </ul>
                </nav>  
                {% endif %}    
            </div>
    </div>
    
</div>


{%endblock content%} 

empleado/templates/persona/list_by_area.html
{% extends 'base.html' %}

{% block title %}
 Lista empleados por departamento
    
{% endblock title %}

{% block content %}
 {% include 'includes/header.html' %}
 <div class=grid-container>
     <div class=grid-x>
         <div class=cell>Empleados por Area</div>
         <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th>NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in listado%}
                    <tr>
                        <td>{{e.id}}</td>
                        <td>{{e.first_name}}</td>
                        <td>{{e.last_name}}</td>
                        <td>{{e.departamento}}</td>
                        <td><a class="button warning" href="{% url 'persona_app:detail_empleado' e.id %}">Ver</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
     </div>
 </div>
    
{% endblock content %}
    
    
<h1>Listado de empleados por Area</h1>
<ul>
    {% for e in listado%}
    <li>
        {{e}}
    </li>
    {% endfor%}
</ul>

empleado/templates/persona/list_by_job.html
<h1> Listado de Empleados por Trabajo</h1>
<ul>
    {%for e in listado%}
    <li>{{e}}</li>
    {%endfor%}
</ul>

empleado/templates/persona/lista_empleados.html
{% extends 'base.html' %}

{%block content%}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de Empleados</h1>
        <div class="cell">
                <table>
                    <thead>
                        <tr>
                            <th width="200">ID</th>
                            <th>NOMBRES</th>
                            <th width="150">APELLIDOS</th>
                            <th width="150">DEPARTAMENTO</th>
                            <th width="150">ACCION</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for e in empleados%}
                        <tr>
                            <td>{{e.id}}</td>
                            <td>{{e.first_name}}</td>
                            <td>{{e.last_name}}</td>
                            <td>{{e.departamento}}</td>
                            <td><a class="button success" href="{% url 'persona_app:modificar' e.id %}">Editar</a></td>
                            <td><a class="button alert" href="{% url 'persona_app:eliminar' e.id %}">Eliminar</a></td></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="cell">
                {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">
                      {% if page_obj.has_previous %}
                      <li class="pagination-previous">
                          <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                      </li>    
                      {% endif %}
                      {% for pagina  in paginator.page_range  %}
                      
                      {% ifequal pagina page_obj.number  %}
                      <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li> 
                      {% else %}
                      <li><a href="?page={{pagina}}" >{{pagina}}</a></li>
                      {% endifequal %}
                          
                         
                      {% endfor %}
                      {% if page_obj.has_next %}
                      <li class="pagination-next">
                          <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                     </li>
                     {% endif %}
                    </ul>
                </nav>  
                {% endif %}    
            </div>
    </div>
    
</div>


{%endblock content%} 

empleado/templates/persona/success.html
<h1>Proceso realizado correctamente</h1>

empleado/templates/persona/update-empleado.html
{% extends 'base.html' %}


{% block title %}
    Editar Empleado
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Modificar Empleado</h1>
        <div class="cell">
            <form class="grid-x grid-margin-x" method="post">{%csrf_token%}
                <div class="cell medium-6">
                    <label>Nombre:
                        {{form.first_name}}
                    </label>
                </div>
                <div class="cell medium-6">
                    <label>Apellido:
                        {{form.last_name}}
                    </label>
                </div>
                <div class="cell medium-6">
                    <label>Trabajo:
                        {{form.job}}
                    </label>
                </div>
                <div class="cell medium-6">
                    <label>Departamento:
                        {{form.departamento}}
                    </label>
                </div>
                <div class="cell medium-6">
                    <label>Habilidades extra:
                        {{form.habilidades}}
                    </label>
                </div>
                <div class="cell">
                    <button type="submit" class="success button">Guardar</button>
                </div>
                 
            </form>
        </div>
    </div>

</div>
    
{% endblock content %}
    
    