empleado/applications/departamento/urls.py
from django.urls import path
from .views import NewDepartamentoView,DepartamentoListView

def DesdeApp(self):
    print('====================Desde aplicación Departamento==================================')

app_name='departamento_app'
urlpatterns = [
    path(
        'departamento-lista/',
        DepartamentoListView.as_view(),
        name='departamento_list'
        ),
    path('new-departamento/',NewDepartamentoView.as_view(),name='nuevo_departamento'),
]

empleado/applications/persona/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


from .views import (
    ListAllEmpleados,
    ListByAreaEmpleado,
    ListEmpleadoByKword,
    ListByTrabajoEmpleado,
    ListHabilidadesEmpleados,
    EmpleadoDetailView,
    EmpleadoCreateView,
    SuccessView,
    EmpleadoUpdateView,
    EmpleadoDeleteView,
    InicioView,
    ListEmpleadosAdmin

)

app_name='persona_app' #estandar de nombre usado por la comunidad
urlpatterns = [
    path('',InicioView.as_view(),name='inicio'),
    path(
        'listar-todo-empleados/',
        ListAllEmpleados.as_view(),
        name="empleados_all"
        ),
    path(
        'listar-by-area/<shorname>/',
         ListByAreaEmpleado.as_view(),
          name='empleados_area'
          ),
    path(
        'lista-empleados-admin/',
         ListEmpleadosAdmin.as_view(),
          name='lista_empleados'
          ),
    path('buscar-empleado/',ListEmpleadoByKword.as_view()),
    path('listar-by-job/', ListByTrabajoEmpleado.as_view()),
    path('listar-habilidades/', ListHabilidadesEmpleados.as_view()),
    path('detail-empleado/<pk>/', EmpleadoDetailView.as_view(), name="detail_empleado"),
    path(
        'add-empleado/',
         EmpleadoCreateView.as_view(),
         name="empleado_add"
         ),
    path('success/', SuccessView.as_view(),name='correcto'),
    path('update-empleado/<pk>',EmpleadoUpdateView.as_view(),name='modificar'),
    path('eliminar-empleado/<pk>',EmpleadoDeleteView.as_view(),name='eliminar')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path,include,re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    # include urls de aplicacion departamento
    re_path('',include('applications.departamento.urls')),
    # include urls de aplicación persona
    re_path('',include('applications.persona.urls')),
    # include urls de la aplicación home
    re_path('',include('applications.home.urls')),
    

]

empleado/applications/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name=models.CharField('Nombre',max_length=50)
    shor_name=models.CharField('Nombre corto', max_length=20)
    anulate = models.BooleanField('Anulado', default=False)
    class Meta:
        verbose_name='Nuestro Departamento'
        verbose_name_plural='Areas de la empresa'
        ordering=['name']
        unique_together=['name','shor_name']


    def __str__(self):
        return str(self.id) + '-' + self.name + '-' + self.shor_name

empleado/applications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shorname = forms.CharField(max_length=20)

empleado/applications/departamento/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import FormView
from.forms import NewDepartamentoForm
from.models import Departamento
# Modelos
from applications.persona.models import Persona



class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamento/lista.html"
    context_object_name='departamentos'

class NewDepartamentoView(FormView):
    template_name='departamento/new_departamento.html'
    form_class=NewDepartamentoForm
    success_url='/'

    def form_valid(self,form):
        depa=Departamento(
            name=form.cleaned_data['departamento'],
            shor_name=['shorname']
        )
        depa.save()
        nombre=form.cleaned_data['nombre']
        apellido=form.cleaned_data['apellidos']
        Persona.objects.create(
            first_name=nombre,
            last_name=apellido,
            job='1',
            departamento=depa

        )
        return super(NewDepartamentoView,self).form_valid(form)

empleado/templates/departamento/lista.html
{% extends 'base.html'%}


{% block title %}
     Lista departamentos
{% endblock title %}
    

{% block content %}
{% include 'includes/header.html' %}
<div class='grid-container'>
    <div class='grid-x'>
        <h1 class='cell'>Lista Departamentos</h1>
        <div class='cell'>
            <table>
                <tbody>
                    
                    {% for departamento in departamentos %}
                    <tr>
                        <td>{{departamento.name}}</td>
                        <td>{{departamento.shor_name}}</td>
                        <td>
                            <a class="button warning" href="{% url 'persona_app:empleados_area' departamento.shor_name  %}">Ver Empleados</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>

</div>
   
{% endblock content %}

    

empleado/templates/departamento/new_departamento.html
{% extends 'base.html' %}


{% block title %}
   Registrar Departamento
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
  <div class="grid-x">
    <h1 class="cell">Registrar Departamento</h1>
    <form class="cell callout grid-x grid-margin-x" method="post">{%csrf_token%}
      <div class="medium-6 cell">
        <label>Nombre:
          {{form.nombre}}
        </label>
      </div>
      <div class="medium-6 cell">
        <label>Apellido:
          {{form.apellidos}}
        </label>
      </div>
      <div class="medium-6 cell">
        <label>Departamento:
          {{form.departamento}}
        </label>
      </div>
      <div class="medium-6 cell">
        <label>Nombre corto:
          {{form.shorname}}
        </label>
      </div>
      <div class="medium-12 cell">
        <button type="submit" class="button">Guardar</button>
      </div>   
  </form>
  </div>

</div>
  
{% endblock content %}
  
  